services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    user: "1000:1000"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD=password #optional
      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=password #optional
      - SUDO_PASSWORD_HASH= #optional
      # - PROXY_DOMAIN=code-server.my.domain #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
      # NEW ADDED
      # - GIT_DISCOVERY_ACROSS_FILESYSTEM=true
    volumes:
      - /scratch/xma12127/shared-scripts:/config/workspace
    ports:
      - 8443:8443
    restart: unless-stopped
